services:
  - type: web
    name: springboot-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-postgres
          property: connectionString
      - key: DATABASE_USER
        fromDatabase:
          name: my-postgres
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: my-postgres
          property: password
      - key: app.jwt.secret
        value: mySuperSecretJWTKey123

databases:
  - name: my-postgres
    plan: free
